In [3]:
from datetime import datetime, date, time, timedelta, timezone
from dateutil import tz
from pendulum import now, timezone
import pandas as pd
import zoneinfo

In [4]:
import os

path_to_data = r"G:\SPECTRUM_SYSTEM\Aeronautas\AZUL\RICARDO LAZZARINI\Auditoria_Calculos"
csv_filename = "escala_e_ricardo_lazzarini_vcp_3394_112017_022023_PRIMEIRA_VERSAO.csv"
csv_path = os.path.join(path_to_data, csv_filename)
tabela = pd.read_csv(csv_path, sep=",")

In [5]:
display(tabela)

,Activity,Checkin,Start,Dep,Arr,End,Checkout,AcVer,DD,CAT,Crew
0,AD5046,2017-11-01 18:55:00,2017-11-01 19:48:00,VCP,POA,2017-11-01 21:37:00,2017-11-02 04:01:00,E95,-,CA,ALESSANDRO DIAS DA SILVA - FO HALAN FRANCISCO ...
1,AD2852,2017-11-01 18:55:00,2017-11-01 22:23:00,POA,CWB,2017-11-01 23:31:00,2017-11-02 04:01:00,E95,-,CA,ALESSANDRO DIAS DA SILVA - FO HALAN FRANCISCO ...
2,AD2852,2017-11-01 18:55:00,2017-11-02 00:02:00,CWB,CGR,2017-11-02 01:43:00,2017-11-02 04:01:00,E95,-,CA,ALESSANDRO DIAS DA SILVA - FO HALAN FRANCISCO ...
3,AD2852,2017-11-01 18:55:00,2017-11-02 02:13:00,CGR,CGB,2017-11-02 03:31:00,2017-11-02 04:01:00,E95,-,CA,ALESSANDRO DIAS DA SILVA - FO HALAN FRANCISCO ...
4,AD2898,2017-11-03 00:20:00,2017-11-03 00:55:00,CGB,SMT,2017-11-03 01:51:00,2017-11-03 02:21:00,E95,-,CA,ALESSANDRO DIAS DA SILVA - FO HALAN FRANCISCO ...
...,...,...,...,...,...,...,...,...,...,...,...
2536,FER,2023-01-28 00:00:00,2023-01-28 00:00:00,VCP,VCP,2023-01-29 00:00:00,2023-01-29 00:00:00,-,-,CA,-
2537,FER,2023-01-29 00:00:00,2023-01-29 00:00:00,VCP,VCP,2023-01-30 00:00:00,2023-01-30 00:00:00,-,-,CA,-
2538,FER,2023-01-30 00:00:00,2023-01-30 00:00:00,VCP,VCP,2023-01-31 00:00:00,2023-01-31 00:00:00,-,-,CA,-
2539,FER,2023-01-31 00:00:00,2023-01-31 00:00:00,VCP,VCP,01FEV23 00:00,01FEV23 00:00,-,-,CA,-
2540,SPS24,01FEV23 00:00,01FEV23 00:00,VCP,VCP,02FEV23 00:00,02FEV23 00:00,-,-,CA,-

LINK MATERIAL UTILIZADO 
https://vaiprogramar.com/como-trabalhar-com-data-hora-python-datetime/#Como_Trabalhar_com_Timezone_em_Python

In [6]:
data = tabela['Checkin'].iloc[0]

data = pd.to_datetime(data).tz_localize(tz.tzlocal())
print(data)
#  2017-11-01 18:55:00-03:00

print(data.tzname())

2017-11-01 18:55:00-03:00
Hora oficial do Brasil